/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-12-06 11:03:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addnewblog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <head>\r\n");
      out.write("          <meta charset=\"UTF-8\">\r\n");
      out.write("          <title>YASH Technologies</title>\r\n");
      out.write("          <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\"> \r\n");
      out.write("          <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("           <link rel=\"stylesheet\" href=\"asset/css/style3.css\"/>\r\n");
      out.write("          \r\n");
      out.write("          <link rel=\"stylesheet\" href=\"asset/css/post-style.css\">\r\n");
      out.write("          <script type=\"text/javascript\" src=\"asset/vendors/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("          <script type=\"text/javascript\" src=\"asset/vendors/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("          <script type=\"text/javascript\" src=\"http://js.nicedit.com/nicEdit-latest.js\"></script> \r\n");
      out.write("          <script type=\"text/javascript\" src=\"asset/js/script.js\"></script>\r\n");
      out.write("          <script type=\"text/javascript\">\r\n");
      out.write("            bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });\r\n");
      out.write("          </script>\r\n");
      out.write("        </head>\r\n");
      out.write("        <body>\r\n");
      out.write("         <!--header starts   -->        \r\n");
      out.write("\r\n");
      out.write("         <div class=\"header\">\r\n");
      out.write("          <header class=\"main-header\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                  <div class=\"col-sm-6\">\r\n");
      out.write("                    <img src=\"asset/images/yash-logo.svg\" class=\"yashlogo pull-left\" alt=\"YAsh Logo\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-sm-6\">\r\n");
      out.write("                    <input type=\"text\" class=\"search-box pull-right\" placeholder=\"Search\">\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </header>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!--header ends -->\r\n");
      out.write("\r\n");
      out.write("        <!-- side navigation starts-->\r\n");
      out.write("\r\n");
      out.write("        <div id=\"wrapper\">\r\n");
      out.write("         <div id=\"sidebar-wrapper\">\r\n");
      out.write("          <ul class=\"sidebar-nav\">\r\n");
      out.write("            <li class=\"sidebar-brand\">\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                Navigation Heading\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"a-side\">\r\n");
      out.write("              <a href=\"#\" ><i class=\"fa fa-home\" aria-hidden=\"true\"></i>Dashboard</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"dropdown a-side\">\r\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"fa fa-columns\" aria-hidden=\"true\"></i>Blog Posts <span class=\"caret\"></span></a>\r\n");
      out.write("              <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("              <li><a href=\"ListBlogController\">All Post</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"addnewblog.jsp\">Add New Post</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"ListCategoryController\">Add New Category</a></li>\r\n");
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"a-side\">\r\n");
      out.write("              <a href=\"userprofile.jsp\" ><i class=\"fa fa-home\" aria-hidden=\"true\"></i>User Profile</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /#sidebar-wrapper--> \r\n");
      out.write("        <!-- /#Page Content--> \r\n");
      out.write("\r\n");
      out.write("        <!-- /Add Page Post starts -->\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"content-header\">\r\n");
      out.write("              <div class=\"pull-left\">\r\n");
      out.write("               <a href=\"#menu-toggle\" class=\"btn\" id=\"menu-toggle\">&#9776;</a>\r\n");
      out.write("               <label >Add New Post</label>\r\n");
      out.write("             </div>\r\n");
      out.write("             <div class=\"pull-right\">\r\n");
      out.write("               <font class=\"d-right\"><a href=\"\"><i class=\"fa fa-home\" aria-hidden=\"true\"></i></a>  / Blog Post / Add New Post</font>\r\n");
      out.write("             </div>\r\n");
      out.write("           </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("          <div class=\"jumbotron\"> \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-xs-12\">\r\n");
      out.write("\r\n");
      out.write("                <form action=\"AddPostController\" method=\"post\"> \r\n");
      out.write("\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"post-title\">Post Title</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"post-title\" placeholder=\"Post Title\" >\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"Description\">Description</label>\r\n");
      out.write("                    <textarea class=\"form-control\" rows=\"8\" name=\"Description\"  ></textarea>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"select-category\">Select Category</label>\r\n");
      out.write("                    <select multiple class=\"form-control\" name=\"select-category\" >\r\n");
      out.write("                      <option value=\"1\">HTML</option>\r\n");
      out.write("                      <option value=\"2\">CSS</option>\r\n");
      out.write("                      <option value=\"3\">Java</option>\r\n");
      out.write("                      <option value=\"4\">Spring</option>\r\n");
      out.write("                      <option value=\"5\">JavaScript</option>\r\n");
      out.write("                      <option value=\"6\">Bootstrap</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <button type=\"submit\" class=\"btn btn-default\">Submit</button> \r\n");
      out.write("                 \t\r\n");
      out.write("                </form>\r\n");
      out.write("                \r\n");
      out.write("             <!--    <form action=\"AddPostController\">\r\n");
      out.write("                \t\t <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("                </form> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- /Add Page Post ends -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /#page-content-wrapper -->        \r\n");
      out.write("\r\n");
      out.write("  <!-- /#wrapper Menu Toggle Script -->\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("    $(\"#menu-toggle\").click(function(e) {\r\n");
      out.write("      e.preventDefault();\r\n");
      out.write("      $(\"#wrapper\").toggleClass(\"toggled\");\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
